-- ACCOUT
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT  (
ID    		NUMBER(38) AUTO_INCREMENT NOT NULL PRIMARY KEY ,
FIRST_NAME  VARCHAR(30) NOT NULL,
LAST_NAME  VARCHAR(30) NOT NULL,
BALANCE    NUMBER(18,2));

INSERT INTO ACCOUNT (FIRST_NAME, LAST_NAME,BALANCE) VALUES ('JACQUES','REMEE',170.00);
INSERT INTO ACCOUNT (FIRST_NAME, LAST_NAME,BALANCE) VALUES ('ALEX','ROY',125.00);
INSERT INTO ACCOUNT (FIRST_NAME, LAST_NAME,BALANCE) VALUES ('MELE','RIGHT',160.00);